### ISSUE TITLE
SASS compiler is failing

### ISSUE THREAD

**Issue by leepowelldev** [bdkjones/CodeKit-1-Old#416]
Simple sass file with the following:

``` css
table.hl {
    margin: 2em 0;
    td.ln { text-align: right; }
}
```

Produces:

Syntax error: Invalid CSS after "2em 0": expected expression (e.g. 1px, bold), was ";"
        on line 2 of /Users/leepowell/Sites/test/sass/theme.sass
  Use --trace for backtrace.
