### ISSUE TITLE
@extend in imported files inside @media only tags

### ISSUE THREAD

**Issue by eightam** [bdkjones/CodeKit-1-Old#463]
The .classToExtended doesn't get extended with .extension.
It seems the problem is the @import in the @media  ...

file.scss

``` css
.extension {
    margin: 10px;
}
@media only screen and (min-width: 600px) {
    @import "external";
}
```

_external.scss

``` css
.classToExtend {
    @extend .extension;
}
```
