### ISSUE TITLE
LESS: Using variables in @import statements breaks Codekits awareness of file imports.

### ISSUE THREAD

**Issue by pedrocorreia** [bdkjones/CodeKit-1-Old#636]
foobar.less:

``` css
@path: "../stuff/";
@import "@{path}_foo.less"
@import "@{path}_bar.less"
@import "@{path}_baz.less"
```

When using variables as part of import paths, codekit no longer is aware of the imports.

In the exemple, compilation of foobar.less is done correctly, but if any of the imported files is changed, Codekit will try to compile it independently.
