### ISSUE TITLE
LESS and strict math

### ISSUE THREAD

**Issue by pustovalov** [bdkjones/CodeKit-1-Old#661]
I turned on the option "Strict math", but it does not work.

input:

``` less
.oval {
  -webkit-border-radius: 20px / 10px;
  -moz-border-radius: 20px / 10px;
  border-radius: 20px / 10px;
}
```

or

``` less
.oval {
  @radius: (20px / 10px);
  -webkit-border-radius: @radius;
  -moz-border-radius: @radius;
  border-radius: @radius;
}
```

output:

``` css
.oval {
  -webkit-border-radius: 2px;
  -moz-border-radius: 2px;
  border-radius: 2px;
}
```
