### ISSUE TITLE
SCSS/SASS - quiet option

### ISSUE THREAD

**Issue by jakob-e** [bdkjones/CodeKit-1-Old#670]
It seems like deprecation warnings makes CodeKit choke - why a **quiet** option would be nice (you are not getting warnings anyways). 

**Example:**

``` SCSS
.extend { content:'A'}
@media all {.extend { content:'B'} }

@mixin extendTest($times){
    @for $i from 0 through $times{
        .test#{$i} { @extend .extend; }
        @media all { .test#{$i} { @extend .extend; } }
    } 
}

// First try this
@include extendTest(20); // Works and output is perfectly valid

// And then this 
// @include extendTest(50); // Nothing, no warnings, just nothing 

```

Best, 
Jakob E
